### ISSUE TITLE
"create new account" functionality is not working

### ISSUE THREAD

**Issue by julianapeace** [EdgeApp/edge-login-ui-rn-demo#1]
After clicking on the "create an account" button from the login screen, we are led to a "Let's get started" page. If you click on "Get started", there is an error message. Link to screenshot: 
https://i.imgur.com/wSyOCUy.png

video: https://slack-files.com/T08U86VNU-FB12NC4SD-142be106fe

**Comment by swansontec** [comment]
It looks like we forgot to run `react-native link`, so some native modules we needed weren't available. Now it seems to work: https://github.com/Airbitz/edge-login-ui-rn-demo/commit/5f4f92863ccd961a103da1a562ba8e6109c16dcb

**Comment by julianapeace** [comment]
Does the command work for [f1800cfb](https://github.com/Airbitz/edge-login-ui-rn-demo/commit/f1800cfb8735ea6e4c2272f150708ad1a0717b75)?
